name: sptnano_min
channels:
  - conda-forge
dependencies:
  - aom
  - asttokens
  - backcall
  - blosc
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-blosc2
  - ca-certificates
  - certifi
  - cfitsio
  - charls
  - charset-normalizer
  - colorama
  - comm
  - contourpy
  - cycler
  - dav1d
  - debugpy
  - decorator
  - executing
  - fonttools
  - freetype
  - giflib
  - hdf5
  - idna
  - imagecodecs
  - imagecodecs-lite
  - imageio
  - importlib-metadata
  - importlib-resources
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jinja2
  - jupyter
  - jupyterlab
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - jxrlib
  - kiwisolver
  - krb5
  - lazy_loader
  - lcms2
  - lerc
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcurl
  - libdeflate
  - libffi
  - libhwloc
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libpng
  - libsodium
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - libzopfli
  - llvmlite
  - looseversion
  - lz4-c
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - mkl
  - munkres
  - nd2reader
  - nest-asyncio
  - networkx
  - numba
  - numexpr
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - patsy
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pooch
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - pure_eval
  - py-cpuinfo
  - pygments
  - pyparsing
  - pysocks
  - pytables
  - python=3.12
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytorch
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - requests
  - scikit-image
  - scipy
  - seaborn
  - seaborn-base
  - setuptools
  - six
  - snappy
  - stack_data
  - statsmodels
  - tbb
  - tifffile
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - unicodedata2
  - urllib3
  - wcwidth
  - wheel
  - widgetsnbextension
  - xmltodict
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - zeromq
  - zfp
  - zipp
  - zlib-ng
  - zstd
  - pip:
      - annotated-types
      - click
      - cloudpickle
      - dask
      - fsspec
      - locket
      - nd2
      - ome-types
      - partd
      - pydantic
      - pydantic-compat
      - pydantic-core
      - pyqt5
      - pyqt5-qt5
      - pyqt5-sip
      - resource-backed-dask-array
      - tiffile
      - toolz
      - xsdata
      - pillow
      - tqdm
      - napari
      - napari-animation
      - datashader
      - scikit-learn
